name: Job Dependencies Workflow
on:
  push:
jobs:
  job_A:
    runs-on: ubuntu-latest
    steps:
      - name: Run Job A
        run: echo "Run Job A"
  job_B:
    runs-on: ubuntu-latest
    steps:
      - name: Run Job B
        run: echo "Run Job B"
  job_C:
    runs-on: ubuntu-latest
    needs: job_A
    steps:
      - name: Run Job C after job A
        run: echo "Run Job C after job A"
  job_D:
    runs-on: ubuntu-latest
    needs: job_B
    steps:
      - name: Run Job D
        run: echo "Run Job D after B"
