name: print hello world in three different shell
on: 
  push:
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world in bash shell
        run: echo "hello world from bash"

  
      - name: print hello world in sh shell
        shell: sh
        run: echo "hello from sh"
        
    
      - name: Print hello world from PowerShell
        shell: pwsh
        run: Write-Output "hello from PowerShell"
