name: my first work flow
on:
  push:
jobs:
  list-directories:
    name: first workflow
    runs-on: ubuntu-latest
  
    steps: 
      - name: check repository
        uses: actions/checkout@v3 
        
      - name: list directories
        run: ls -la
